import type { Metadata } from "next";
import "./globals.css";
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Prowser Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark:bg-neutral-800 dark:text-white"
    >
      <body className="min-h-screen">
        <header className="dark:bg-neutral-900 w-full h-20 grid grid-cols-2 grid-rows-1 px-8">
          <div className="flex items-center my-auto">
            <Image
              src="/logo_80.png"
              alt="test"
              width={45}
              height={45}
              className="me-5"
            />
            <label className="text-3xl">Portfolio - Julian Verwoerd</label>
          </div>
          <div className="flex items-center justify-end my-auto gap-12 text-xl px-5">
            <Link href="/" className="cursor-pointer transition-colors hover:text-purple-800">
              Home
            </Link>
            <Link href="/over-mij" className="cursor-pointer transition-colors hover:text-purple-800">
              Over mij
            </Link>
            <Link href="/projecten" className="cursor-pointer transition-colors hover:text-purple-800">
              Projecten
            </Link>
            <Link href="/contact" className="cursor-pointer transition-colors hover:text-purple-800">
              Contact
            </Link>
          </div>
        </header>
        <main className="px-50 py-10 min-h-[calc(100vh-5rem)]">
          {children}
        </main>
      </body>
    </html>
  );
}
