import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Portfolio - Julian Verwoerd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="nl"
      className="dark:bg-neutral-900 dark:text-white"
    >
      <body className="min-h-screen">
        <Header />
        <main className="px-60 py-15 min-h-[calc(100vh-5rem)]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
