import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Prowser Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark:bg-neutral-900 dark:text-white"
    >
      <body className="min-h-screen">
        <Header />
        <main className="px-50 py-15 min-h-[calc(100vh-5rem)]">
          {children}
        </main>
      </body>
    </html>
  );
}
